FROM runpod/pytorch:2.4.0-py3.11-cuda12.4.1-devel-ubuntu22.04

# Systempakete & Python vorbereiten
RUN apt-get update && apt-get install -y git wget curl ffmpeg libgl1 libglib2.0-0 && \
    pip install --upgrade pip

# ComfyUI klonen
WORKDIR /workspace
RUN git clone https://github.com/comfyanonymous/ComfyUI.git /workspace/ComfyUI

# ComfyUI Requirements installieren
RUN pip install -r /workspace/ComfyUI/requirements.txt
RUN pip install torchvision==0.15.2
RUN apt-get update && apt-get install -y ninja-build cmake build-essential git && \
    pip install --no-cache-dir git+https://github.com/facebookresearch/xformers.git@main
RUN pip install jupyterlab

# Ports für ComfyUI (8188) + Jupyter (8888)
EXPOSE 8188
EXPOSE 8888

# Start ComfyUI per Default (Jupyter manuell bei Bedarf)
CMD ["python3", "/workspace/ComfyUI/main.py", "--listen", "--port", "8188", "--output-directory", "/workspace/output", "--input-directory", "/workspace/input"]
